### ISSUE TITLE
Correct Typo Errors

### ISSUE THREAD

**Issue by abdoachhoubi** [abdoachhoubi/nodejs-notes#1]
I need someone to go through the markdown files and check if there are any typo errors and correct them!

**Comment by FrancoFrancis** [comment]
Awesome I would love to do that

**Comment by Imran-Khalid-code** [comment]
Do you still require any help on this?

**Comment by abdoachhoubi** [comment]
@FrancoFrancis
Thanks!
You can fork the project anytime and start working on this issue!

**Comment by abdoachhoubi** [comment]
@Imran-Khalid-code
Yes!
And I'm adding new files everyday, so whenever you'd like to work on this issue, I'll  be ready to review your PRs.

And thanks for considering helping me out with this!

**Comment by FrancoFrancis** [comment]
Awesome will do that, sorry for replying late I went to church just coming back.
